#!/bin/bash

RABBIT_PASS=$(openssl rand -base64 24)
KEYSTONE_DBPASS=$(openssl rand -base64 24)
ADMIN_TOKEN=$(openssl rand -base64 24)
ADMIN_PASS=$(openssl rand -base64 24)
GLANCE_DBPASS=$(openssl rand -base64 24)
GLANCE_PASS=$(openssl rand -base64 24)
NOVA_DBPASS=$(openssl rand -base64 24)
NOVA_PASS=$(openssl rand -base64 24)
DASH_DBPASS=$(openssl rand -base64 24)
CINDER_DBPASS=$(openssl rand -base64 24)
CINDER_PASS=$(openssl rand -base64 24)
NEUTRON_DBPASS=$(openssl rand -base64 24)
NEUTRON_PASS=$(openssl rand -base64 24)
HEAT_DBPASS=$(openssl rand -base64 24)
HEAT_PASS=$(openssl rand -base64 24)
CEILOMETER_DBPASS=$(openssl rand -base64 24)
CEILOMETER_PASS=$(openssl rand -base64 24)
TROVE_DBPASS=$(openssl rand -base64 24)
TROVE_PASS=$(openssl rand -base64 24)
DEMO_PASS=$(openssl rand -base64 24)
METADATA_PASS=$(openssl rand -base64 24)

echo "export RABBIT_PASS=\"${RABBIT_PASS}\""
echo "export KEYSTONE_DBPASS=\"${KEYSTONE_DBPASS}\""
echo "export ADMIN_TOKEN=\"${ADMIN_TOKEN}\""
echo "export ADMIN_PASS=\"${ADMIN_PASS}\""
echo "export GLANCE_DBPASS=\"${GLANCE_DBPASS}\""
echo "export GLANCE_PASS=\"${GLANCE_PASS}\""
echo "export NOVA_DBPASS=\"${NOVA_DBPASS}\""
echo "export NOVA_PASS=\"${NOVA_PASS}\""
echo "export DASH_DBPASS=\"${DASH_DBPASS}\""
echo "export CINDER_DBPASS=\"${CINDER_DBPASS}\""
echo "export CINDER_PASS=\"${CINDER_PASS}\""
echo "export NEUTRON_DBPASS=\"${NEUTRON_DBPASS}\""
echo "export NEUTRON_PASS=\"${NEUTRON_PASS}\""
echo "export HEAT_DBPASS=\"${HEAT_DBPASS}\""
echo "export HEAT_PASS=\"${HEAT_PASS}\""
echo "export CEILOMETER_DBPASS=\"${CEILOMETER_DBPASS}\""
echo "export CEILOMETER_PASS=\"${CEILOMETER_PASS}\""
echo "export METADATA_PASS=\"${METADATA_PASS}\""
echo "export DEMO_PASS=\"${DEMO_PASS}\""